In [2]:
import re
import numpy as np
import pandas as pd
import collections

In [3]:
data = pd.read_csv("total.csv")
data.head()

,No,Title,Author,Department,Date,clue,know,familiar,Read,Share,Register,Max_layers
0,1,工地直播间（二） | 名匠装饰工地巡展,吴伟,地市营销总部岳阳营销部市场C组,2018-10-06 15:02:13.0,0,0,1,1,0,0,1
1,2,自装？亲戚装？装饰公司装？终于有让人信服的答案了,蒋小村,望城店网销部长沙区,2018-10-06 11:09:16.0,0,0,1,1,0,0,1
2,3,玄关除了装鞋柜没别的选择吗？这样装最实用！,李云俊,星沙店市场部二区长沙区,2018-10-06 10:40:16.0,11,1,1,16,0,0,1
3,4,装修知识 | 嫌空间太小了？简单几招，让你家分分钟变大！,谭赛花,城东店网络部长沙区,2018-10-02 09:39:52.0,7,3,0,16,0,0,1
4,5,2018年度品质壕装节,许源,地市营销总部常德城西营销部,2018-09-29 15:19:42.0,65,0,5,107,21,0,8

In [4]:
data_0=data[~(data.Read==0)]

In [5]:
data_0

,No,Title,Author,Department,Date,clue,know,familiar,Read,Share,Register,Max_layers
0,1,工地直播间（二） | 名匠装饰工地巡展,吴伟,地市营销总部岳阳营销部市场C组,2018-10-06 15:02:13.0,0,0,1,1,0,0,1
1,2,自装？亲戚装？装饰公司装？终于有让人信服的答案了,蒋小村,望城店网销部长沙区,2018-10-06 11:09:16.0,0,0,1,1,0,0,1
2,3,玄关除了装鞋柜没别的选择吗？这样装最实用！,李云俊,星沙店市场部二区长沙区,2018-10-06 10:40:16.0,11,1,1,16,0,0,1
3,4,装修知识 | 嫌空间太小了？简单几招，让你家分分钟变大！,谭赛花,城东店网络部长沙区,2018-10-02 09:39:52.0,7,3,0,16,0,0,1
4,5,2018年度品质壕装节,许源,地市营销总部常德城西营销部,2018-09-29 15:19:42.0,65,0,5,107,21,0,8
5,6,装修知识 | 嫌空间太小了？简单几招，让你家分分钟变大！,伍洲,地市营销总部常德澧县营销部,2018-09-21 21:56:52.0,3,0,0,3,0,0,1
6,7,这些常见的装修错误设计，你中招了吗？,伍洲,地市营销总部常德澧县营销部,2018-09-21 19:35:24.0,1,0,0,1,0,0,1
7,8,榻榻米床+柜子这样设计，尽情享受惬意空间！,闵玲,城东店网络部长沙区,2018-09-19 17:50:23.0,1,0,1,3,0,0,1
8,9,马尔默：空间虽小，却因绿植与家具，营造出灵动与生机,高琳,梅溪湖店长沙区,2018-09-14 20:58:00.0,33,0,1,36,1,0,3
9,10,名匠特权日 尊享品质家 | 9月16日名匠装饰2018消费者特权,高琳,梅溪湖店长沙区,2018-09-14 20:29:12.0,34,0,3,47,8,0,4
10,11,2018最完整家装尺寸大全，装修前一定要看！,李云俊,星沙店市场部二区长沙区,2018-09-13 10:51:04.0,17,0,1,23,0,0,1
11,12,名匠特权日 尊享品质家 | 9月16日名匠装饰2018消费者特权,王广凤,地市营销总部电商部郴州电商部,2018-09-12 11:44:32.0,6,0,3,9,1,0,1
12,13,名匠品质 | 2018，坚守初心，砥砺前行，将工地巡检进行到底！,周志刚,城东店北二区长沙区,2018-09-11 20:08:53.0,1,0,1,21,0,0,1
13,14,最实用装修主材大盘点！,李云俊,星沙店市场部二区长沙区,2018-09-11 19:44:27.0,7,0,1,8,0,0,1
14,15,家装达人教你1分钟搞懂【整体家装】,彭银花,地市营销总部电商部娄底电商部,2018-09-09 10:07:58.0,29,0,1,38,29,0,3
15,16,千金难买早知道，装修时最不能省钱的四个方面！,李玲洁,南店网销部长沙区,2018-09-07 17:58:12.0,6,1,3,12,1,0,2
16,17,22款衣柜设计，这样的衣柜简直好看到逆天！,李玲洁,南店网销部长沙区,2018-09-07 17:50:19.0,10,0,2,13,0,0,1
17,18,找装修队还是装修公司，在此之前先问自己4个问题！,陈章,南店网销部长沙区,2018-09-07 16:50:24.0,1,0,2,3,0,0,1
18,19,新中式，有禅意、有质感，更符合现代人审美！,周志刚,城东店北二区长沙区,2018-09-05 17:18:32.0,47,0,13,87,4,0,2
19,20,榻榻米床+柜子这样设计，尽情享受惬意空间！,任江平,城东店北二区长沙区,2018-09-05 17:03:13.0,18,0,3,25,1,0,1
20,21,名匠雅居 | 美到骨子里的新中式雅居，演绎独具韵味的东方美！,周志刚,城东店北二区长沙区,2018-09-05 17:00:31.0,23,1,5,35,1,0,2
21,22,名匠雅居 | 90㎡北欧风格演绎！,周志刚,城东店北二区长沙区,2018-09-05 16:53:47.0,56,1,14,98,1,0,1
22,23,好的装修到底是什么样的，看看业主们是怎么说的！,刘江南,地市营销总部衡阳西渡店营销部西渡店市场二区,2018-09-05 12:14:48.0,4,0,0,4,0,0,1
23,24,如何判断瓷砖的优劣,陈章,南店网销部长沙区,2018-09-04 21:49:29.0,1,0,1,4,0,0,1
24,25,又到了最适合装修的9月，您还考虑什么呢？,张惠,南店网销部长沙区,2018-09-04 19:04:14.0,9,0,3,18,11,0,2
25,26,设计沟通攻略｜装修前如何与设计师沟通？,邵小燕,地市营销总部耒阳网络部耒阳网络部,2018-09-04 18:23:41.0,32,0,2,36,3,0,2
26,27,装修知识 | 嫌空间太小了？简单几招，让你家分分钟变大！,蒋开兰,地市营销总部电商部邵阳电商部,2018-09-04 10:08:06.0,0,0,1,1,4,0,1
27,28,这些常见的装修错误设计，你中招了吗？,蒋开兰,地市营销总部电商部邵阳电商部,2018-09-04 10:07:12.0,0,0,1,1,0,0,1
28,29,又到了最适合装修的9月了，您还在犹豫什么!,陈正,南店网销部长沙区,2018-09-02 11:10:02.0,6,0,1,10,2,0,2
29,30,你家阳台还用来放拖把？看看怎么装好看又实用！,李云俊,星沙店市场部二区长沙区,2018-09-02 10:12:29.0,29,0,4,38,2,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...
10398,10399,名匠装饰15周年店庆，2000万豪礼等您拿！,周培,城东店东二区长沙区,2017-06-28 15:26:04.0,6,1,1,11,1,0,1
10399,10400,名匠装饰15周年店庆，2000万豪礼等您拿！,陈俊峰,城东店北二区长沙区,2017-06-28 15:25:58.0,2,0,2,8,1,0,2
10400,10401,像这样的房子，装修多少预算才合适,曾新,城东店东二区长沙区,2017-06-28 15:25:22.0,10,0,0,10,0,0,1
10401,10402,名匠装饰15周年店庆，2000万豪礼等您拿！,陈骞（陈骞亚）,城东店总设计部长沙区,2017-06-28 15:25:07.0,1,0,0,1,0,0,1
10402,10403,名匠装饰15周年店庆，2000万豪礼等您拿！,赵政国（赵洁）,城东店东一区长沙区,2017-06-28 15:23:30.0,2,0,0,3,1,0,1
10403,10404,名匠装饰15周年店庆，2000万豪礼等您拿！,肖瑨,城东店设计五部长沙区,2017-06-28 15:15:11.0,3,0,1,6,0,0,1
10404,10405,名匠装饰15周年店庆，2000万豪礼等您拿！,朱兴,城东店东一区长沙区,2017-06-28 15:14:53.0,115,18,12,214,51,0,7
10405,10406,名匠装饰15周年店庆，2000万豪礼等您拿！,刘文文,城东店北二区长沙区,2017-06-28 15:11:04.0,2,0,1,11,2,0,1
10406,10407,名匠装饰15周年店庆，2000万豪礼等您拿！,危长发,城东店东一区长沙区,2017-06-28 15:10:33.0,14,2,1,21,4,0,4
10407,10408,名匠装饰15周年店庆，2000万豪礼等您拿！,刘丹,城东店设计四部长沙区,2017-06-28 15:10:09.0,6,0,0,9,1,0,2
10408,10409,名匠装饰15周年店庆，2000万豪礼等您拿！,张文超,城东店北一区长沙区,2017-06-28 15:09:11.0,12,0,2,21,6,0,4
10409,10410,名匠装饰15周年店庆，2000万豪礼等您拿！,陈锦,城东店设计四部长沙区,2017-06-28 15:03:45.0,3,0,0,3,0,0,1
10410,10411,名匠装饰15周年店庆，2000万豪礼等您拿！,刘小芳,城东店设计四部长沙区,2017-06-28 15:02:46.0,17,1,0,22,6,0,3
10411,10412,像这样的房子，装修多少预算才合适,陈锦,城东店设计四部长沙区,2017-06-28 15:02:10.0,3,0,0,3,0,0,1
10412,10413,名匠精工丨在名匠，为您家施工的到底是怎样一群人？,陈锦,城东店设计四部长沙区,2017-06-28 15:01:38.0,1,0,0,1,0,0,1
10413,10414,名匠装饰15周年店庆，2000万豪礼等您拿！,刘文文,城东店北二区长沙区,2017-06-28 15:00:42.0,2,0,1,5,1,0,2
10414,10415,名匠装饰15周年店庆，2000万豪礼等您拿！,徐娜,城东店设计二部长沙区,2017-06-28 14:57:22.0,15,0,1,20,4,0,3
10415,10416,名匠装饰15周年店庆，2000万豪礼等您拿！,姚萍娟,城东店设计二部长沙区,2017-06-28 14:55:35.0,28,0,0,32,5,0,3
10416,10417,名匠装饰15周年店庆，2000万豪礼等您拿！,臧奇,城东店东一区长沙区,2017-06-28 14:53:28.0,0,0,1,1,0,0,1
10417,10418,名匠装饰15周年店庆，2000万豪礼等您拿！,黄勇,城东店设计二部长沙区,2017-06-28 14:53:20.0,43,0,1,64,13,0,7
10418,10419,名匠装饰15周年店庆，2000万豪礼等您拿！,肖平娇,城东店北一区长沙区,2017-06-28 14:52:10.0,6,0,1,9,0,0,1
10419,10420,下雨天宅里？万元巨款你不准备要了吗？,闵玲,城东店网络部长沙区,2017-06-28 14:51:36.0,16,2,3,55,13,0,3
10420,10421,名匠精工丨在名匠，为您家施工的到底是怎样一群人？,陈睿,城东店北一区长沙区,2017-06-28 14:21:41.0,11,0,1,16,2,0,3
10421,10422,名匠精工丨在名匠，为您家施工的到底是怎样一群人？,周幸,长沙区,2017-06-28 13:13:10.0,53,0,2,74,10,1,3
10422,10423,名匠装饰15周年狂欢月,周幸,长沙区,2017-06-28 13:00:58.0,13,0,1,18,4,0,4
10423,10424,名匠装饰15周年狂欢月，抢定从速！,周幸,长沙区,2017-06-28 11:01:46.0,4,0,0,13,0,0,1
10424,10425,像这样的房子，装修多少预算才合适,王婷,电商中心长沙区,2017-06-27 17:37:37.0,1,0,1,13,0,1,1
10425,10426,名匠装饰15周年店庆，2000万豪礼等您拿！,王婷,电商中心长沙区,2017-06-27 17:06:29.0,0,0,1,6,0,0,1
10426,10427,1111,傅健,NaN,2017-06-24 14:11:29.0,0,0,3,3,5,0,3
10427,10428,111,傅健,NaN,2017-06-24 13:43:18.0,3,0,1,12,6,1,2

In [6]:
c=collections.Counter(data_0.Author)
c=c.most_common()
author=[]
count=[]
for i in c:
    if i[1]>35:
        author.append(i[0])
        count.append(i[1])
        
        
c #copy to create count.csv

[('薛剑锋', 255),
 ('潘浩', 212),
 ('彭超', 212),
 ('曾小纾', 211),
 ('蒋小村', 209),
 ('占登文', 200),
 ('吴俊雄', 191),
 ('刘江南', 189),
 ('黄蓉', 184),
 ('蔡方纯', 177),
 ('王广凤', 166),
 ('陈挺魁', 164),
 ('谭梁燕', 162),
 ('潘佳', 160),
 ('江蓉', 153),
 ('王婷', 150),
 ('闵玲', 149),
 ('张显政', 149),
 ('彭娟', 132),
 ('丁妮', 128),
 ('周健', 127),
 ('吴灿', 127),
 ('龙海', 121),
 ('张琼', 119),
 ('黎勇', 108),
 ('曾立', 107),
 ('周志刚', 99),
 ('陈亚琴', 99),
 ('陈章', 93),
 ('罗明洲', 85),
 ('饶广峰', 85),
 ('石磊', 74),
 ('欧旅', 74),
 ('蔡娇', 72),
 ('唐操', 72),
 ('曾凡忠', 70),
 ('李祥', 69),
 ('吴红菲', 67),
 ('彭堂君', 63),
 ('曾妹', 61),
 ('林雪梅', 60),
 ('谢爱华', 60),
 ('谭赛花', 58),
 ('+章珊', 57),
 ('李樊宙', 56),
 ('刘真', 55),
 ('戴丽丽\xa0', 52),
 ('李荣泉', 52),
 ('肖金恒', 50),
 ('肖华', 50),
 ('唐文启', 49),
 ('杨州', 47),
 ('张惠', 46),
 ('左都美', 46),
 ('陈正', 44),
 ('周玲', 44),
 ('邓美荣', 44),
 ('冯胜禄', 44),
 ('彭银花', 43),
 ('赵杨', 43),
 ('吴梦娇', 42),
 ('王俏月', 41),
 ('谢娟', 40),
 ('李杰', 39),
 ('熊喜', 39),
 ('陈勇', 38),
 ('胡善国', 37),
 ('孙功平', 36),
 ('李跃文', 35),
 ('李发扬', 34),
 ('王地', 34),
 ('廖唯', 34),
 ('李玲洁', 33),
 ('唐寅瑞', 33),
 ('冯大鹏', 32),
 ('刘涛', 32),
 ('伍志霞', 31),
 ('马桢', 30),
 ('张羽鹏', 30),
 ('彭四海', 30),
 ('伍洲', 29),
 ('邵小燕', 29),
 ('胡朝', 29),
 ('李梓', 28),
 ('曾新', 28),
 ('李勇红', 27),
 ('朱媛', 27),
 ('谢银花', 27),
 ('李云俊', 26),
 ('杨光', 26),
 ('江常春', 26),
 ('蒋开兰', 25),
 ('郭俊芝', 25),
 ('李荣华', 25),
 ('梁荷香', 24),
 ('刘喻', 24),
 ('彭敏', 24),
 ('康富兴', 24),
 ('郭佳', 23),
 ('蒋平健', 23),
 ('何波', 23),
 ('郭云', 23),
 ('周秋香', 23),
 ('王新华', 22),
 ('李星锗', 22),
 ('王宏', 22),
 ('谈晓', 22),
 ('颜琳', 22),
 ('彭桂云', 22),
 ('周敏', 21),
 ('李凡丽', 21),
 ('卢芳', 21),
 ('李栗', 21),
 ('张谷丰', 20),
 ('姚权聪 ', 19),
 ('刘娇', 19),
 ('郭异文', 19),
 ('朱晓奇', 19),
 ('吕绍贤', 19),
 ('何纯勇', 19),
 ('谭珊珊', 19),
 ('陈金朋', 19),
 ('熊巧', 18),
 ('李盼', 18),
 ('罗金莉', 18),
 ('谭玉英', 17),
 ('刘双全', 17),
 ('傅健', 17),
 ('杨向霞', 17),
 ('陈齐', 17),
 ('潘飞龙', 17),
 ('胡建枚', 17),
 ('李朝伟', 17),
 ('乐春桃', 17),
 ('龙江', 16),
 ('胡勇+', 16),
 ('谢李珊', 16),
 ('何莎莎', 16),
 ('杨胜鲜', 16),
 ('袁锦根', 16),
 ('秦园园', 15),
 ('胡波', 15),
 ('田莉', 15),
 ('刘少杰', 15),
 ('简学良', 15),
 ('黄小凤', 15),
 ('周远鹏', 15),
 ('苏晗', 15),
 ('陆文俊', 14),
 ('任花', 14),
 ('凌美丽', 14),
 ('龙彩虹', 14),
 ('王木兰', 14),
 ('刘国文', 14),
 ('邓鑫', 14),
 ('周幸', 13),
 ('杨婉霞', 13),
 ('马世美', 13),
 ('卢彬', 13),
 ('刘英', 13),
 ('朱泉', 13),
 ('刘三军', 13),
 ('沈勇', 13),
 ('高琳', 12),
 ('蒋星', 12),
 ('赖润松', 12),
 ('尹广', 12),
 ('王为(王有为）', 12),
 ('王姣姣', 12),
 ('唐晓敏', 12),
 ('彭犇', 12),
 ('陈圣娇', 12),
 ('谢凯', 12),
 ('吴伟', 11),
 ('黄文', 11),
 ('赵之兰', 11),
 ('谭丽萍', 11),
 ('刘平', 11),
 ('黄红梅', 11),
 ('王明智', 11),
 ('姚芬', 11),
 ('赵林', 11),
 ('李籽港', 11),
 ('陈美林', 11),
 ('李鹏', 11),
 ('齐希', 10),
 ('李芙蓉', 10),
 ('兰巧军', 10),
 ('彭建芳', 10),
 ('向炼', 10),
 ('吴代航', 10),
 ('黄荷秀', 10),
 ('孙丹', 10),
 ('袁姜满', 10),
 ('杨杰', 10),
 ('罗阳苗', 10),
 ('姚振华', 10),
 ('王记刚', 10),
 ('周志勇', 10),
 ('陈锦', 10),
 ('彭明明', 10),
 ('李觉航', 9),
 ('赵滔', 9),
 ('文铭', 9),
 ('罗婷', 9),
 ('李曦', 9),
 ('钟函', 9),
 ('陈璇', 9),
 ('杨婷', 9),
 ('张小爱', 9),
 ('彭礼丹', 9),
 ('伍胜', 9),
 ('袁翠柳', 8),
 ('宋倩妮', 8),
 ('张文超', 8),
 ('王博瑞', 8),
 ('王国庆', 8),
 ('吴杨琦', 8),
 ('刘斌', 8),
 ('代晶', 8),
 ('王艳', 8),
 ('任江平', 7),
 ('肖海霞', 7),
 ('彭洪刚', 7),
 ('郭博杰', 7),
 ('柳柳', 7),
 ('石珑', 7),
 ('张琪', 7),
 ('陈坤', 7),
 ('龙爱香', 7),
 ('肖杰', 7),
 ('刘益', 7),
 ('刘三菊', 7),
 ('刘文文', 7),
 ('彭帅', 7),
 ('陆杨', 7),
 ('龚春', 7),
 ('张丹', 7),
 ('陈华', 7),
 ('王琪', 7),
 ('李其军', 6),
 ('吉祥', 6),
 ('张海', 6),
 ('高梧', 6),
 ('黄玲', 6),
 ('易赐', 6),
 ('曾科', 6),
 ('肖祥祝', 6),
 ('徐象', 6),
 ('郝成', 6),
 ('张威', 6),
 ('王武', 6),
 ('李立志', 6),
 ('雷博文', 6),
 ('夏雨珊', 6),
 ('陈郁', 6),
 ('孟志鹏', 6),
 ('姚兰丽', 6),
 ('赵雪晴', 6),
 ('廖元园', 6),
 ('徐静娴', 6),
 ('白俊', 6),
 ('徐坤', 6),
 ('何慧', 6),
 ('刘祥祖', 6),
 ('万延和', 5),
 ('邹鹏', 5),
 ('周方勇', 5),
 ('郭芳', 5),
 ('黄勇', 5),
 ('唐孔明', 5),
 ('肖智', 5),
 ('刘小梅', 5),
 ('苏楠', 5),
 ('钱进', 5),
 ('肖平娇', 5),
 ('肖雄', 5),
 ('聂叶辉', 5),
 ('邓凯伦', 5),
 ('何利君', 5),
 ('钟懿', 5),
 ('王子璇', 5),
 ('刘鹃', 5),
 ('韩丹', 5),
 ('刘毅', 5),
 ('张敏', 5),
 ('罗玉霞', 5),
 ('谢巧', 5),
 ('丁丽美', 5),
 ('曹丽蓉', 5),
 ('黄世裕', 5),
 ('周小兰', 5),
 ('郭威', 5),
 ('戴振华', 5),
 ('胡仁云', 5),
 ('刘德成', 5),
 ('杨倩', 5),
 ('蒋映军', 5),
 ('杨胜', 5),
 ('黄小虎', 5),
 ('徐娜', 5),
 ('王情', 4),
 ('魏义康', 4),
 ('凌慧', 4),
 ('危长发', 4),
 ('灿', 4),
 ('李礼', 4),
 ('朱海涛', 4),
 ('苏有前', 4),
 ('李河根', 4),
 ('叶敏', 4),
 ('曹攀', 4),
 ('江雅萍', 4),
 ('李爱', 4),
 ('喻晓峰', 4),
 ('左婷', 4),
 ('张珍', 4),
 ('董利', 4),
 ('周亚', 4),
 ('蔡刘君', 4),
 ('曾裕华（曾杰）', 4),
 ('魏凯', 4),
 ('谢永福', 4),
 ('曹衡辉', 4),
 ('刘先梅', 4),
 ('刘欧', 4),
 ('夏见尧', 4),
 ('李国财', 4),
 ('谢秋兰', 4),
 ('周良宏', 4),
 ('邓蜜桃', 4),
 ('胡拥军', 4),
 ('周中威', 4),
 ('唐坤', 4),
 ('杨华伟', 4),
 ('冯倩', 4),
 ('聂新玉', 4),
 ('赵胜坤', 4),
 ('童峰（童细明）', 4),
 ('毛张霞', 4),
 ('蒋梓良', 4),
 ('吴宇', 4),
 ('许源', 3),
 ('屈斌', 3),
 ('何源', 3),
 ('朱耀光', 3),
 ('罗亚丽', 3),
 ('孙发贵', 3),
 ('郭文凤', 3),
 ('陶立', 3),
 ('刘保建', 3),
 ('杨向辉', 3),
 ('彭庆元', 3),
 ('陈春仙', 3),
 ('张玉华', 3),
 ('皮丽君', 3),
 ('刘健', 3),
 ('徐婉婷', 3),
 ('曹宁波', 3),
 ('胡赛', 3),
 ('张文娇', 3),
 ('周浪', 3),
 ('刘水林', 3),
 ('宋元', 3),
 ('高凤', 3),
 ('陈勇杰', 3),
 ('李振辉', 3),
 ('张玲', 3),
 ('廖慕橙', 3),
 ('蔡燕', 3),
 ('李孟杰', 3),
 ('廖深根', 3),
 ('刘念', 3),
 ('杨银飞', 3),
 ('许宸畅', 3),
 ('康双峰', 3),
 ('刘金花', 3),
 ('易卫平', 3),
 ('胡杨', 3),
 ('刘增科', 3),
 ('熊娄红', 3),
 ('谢群', 3),
 ('屈敦芳', 3),
 ('刘栋梁', 3),
 ('李振华', 3),
 ('王黎明', 3),
 ('成莹', 3),
 ('黄滔', 3),
 ('胡珍', 3),
 ('李威', 3),
 ('谢成名', 3),
 ('黄丽君', 3),
 ('付智和', 3),
 ('刘佳宝', 3),
 ('陈莎', 3),
 ('熊彬', 3),
 ('康港辉', 3),
 ('臧奇', 3),
 ('彭毅昌', 2),
 ('彭浩淼', 2),
 ('潇潇', 2),
 ('李丹', 2),
 ('段理梁', 2),
 ('张杰', 2),
 ('戴勇', 2),
 ('林志姣', 2),
 ('唐海华', 2),
 ('胡淼', 2),
 ('彭丹', 2),
 ('肖骏', 2),
 ('刘炯', 2),
 ('陆关霖', 2),
 ('袁浪', 2),
 ('陈睿', 2),
 ('廖旺泉', 2),
 ('邓运武', 2),
 ('周孝和', 2),
 ('谈艳芳', 2),
 ('周雅俐', 2),
 ('吴超群', 2),
 ('秦涌海', 2),
 ('苏思妮', 2),
 ('邓银辉', 2),
 ('刘洋', 2),
 ('张政', 2),
 ('陈杰', 2),
 ('邓丽娟', 2),
 ('杨静', 2),
 ('蒋小倩', 2),
 ('陈俊峰', 2),
 ('易萌萌', 2),
 ('杜晶涛', 2),
 ('张先业', 2),
 ('袁建国', 2),
 ('曾华溢', 2),
 ('杨波', 2),
 ('廖云飞', 2),
 ('闵雪', 2),
 ('邹静思', 2),
 ('胡向阳', 2),
 ('严佳琪', 2),
 ('李伟', 2),
 ('张力', 2),
 ('李甜', 2),
 ('任凡', 2),
 ('张杉', 2),
 ('严仁秋', 2),
 ('贺泽文', 2),
 ('胡建', 2),
 ('徐凯东', 2),
 ('易俊杰', 2),
 ('胡烈', 2),
 ('高信', 2),
 ('颜林芳', 2),
 ('胡明波', 2),
 ('邱喜', 2),
 ('童波', 2),
 ('李杜', 2),
 ('刘星', 2),
 ('毕子星', 2),
 ('冯丽', 2),
 ('刘琴', 2),
 ('马光前', 2),
 ('吴振华', 2),
 ('李小龙', 2),
 ('黄繁荣', 2),
 ('张静', 2),
 ('张灿明', 2),
 ('胡佳', 2),
 ('肖丽萍', 2),
 ('夏权', 2),
 ('丁金雄', 2),
 ('刘人瑞', 2),
 ('余赛夫', 2),
 ('刘丹', 2),
 ('刘仁文', 2),
 ('陈伟祥', 2),
 ('杨佳熠', 2),
 ('刘恒', 2),
 ('田涵冰', 2),
 ('姚萍娟', 2),
 ('朱承宇', 2),
 ('王晓涛', 2),
 ('王梓臣', 2),
 ('李仁', 2),
 ('肖科', 2),
 ('刘光宇', 2),
 ('郑杨', 2),
 ('唐超', 2),
 ('田浩佑（田源）', 2),
 ('王斌', 2),
 ('陈硕', 2),
 ('马云飞', 1),
 ('粟扬扬', 1),
 ('娄遵议', 1),
 ('罗洁', 1),
 ('胡浩然', 1),
 ('秦敏霞', 1),
 ('胡平安', 1),
 ('赖燕', 1),
 ('邹裕', 1),
 ('谭双顺', 1),
 ('龙定中', 1),
 ('张益', 1),
 ('吴培任', 1),
 ('李平', 1),
 ('朱懿骞', 1),
 ('罗文专', 1),
 ('谢胜兰', 1),
 ('蒋海艳', 1),
 ('盘先通', 1),
 ('郭玉梅', 1),
 ('蒋伟文', 1),
 ('姜津玉', 1),
 ('董志豪', 1),
 ('唐果', 1),
 ('李斌', 1),
 ('雷芳', 1),
 ('唐俊', 1),
 ('杨亚飞', 1),
 ('王炳华', 1),
 ('李媛', 1),
 ('曾唯', 1),
 ('王鹏飞', 1),
 ('胡思思', 1),
 ('何斌', 1),
 ('郭春方', 1),
 ('全小辉', 1),
 ('胡善建', 1),
 ('方维', 1),
 ('谭三祥', 1),
 ('刘行恩', 1),
 ('廖海琼', 1),
 ('刘兆东', 1),
 ('蒋宇', 1),
 ('曾磊', 1),
 ('李广华', 1),
 ('谢显峰', 1),
 ('宋静', 1),
 ('骆威', 1),
 ('欧阳丹', 1),
 ('何思华', 1),
 ('李毅', 1),
 ('洪毅', 1),
 ('夏俊', 1),
 ('钱亮', 1),
 ('王章友', 1),
 ('傅雅丽', 1),
 ('曾罗', 1),
 ('刘甜', 1),
 ('李海南', 1),
 ('薛俊达', 1),
 ('蒋春香', 1),
 ('钟琴', 1),
 ('聂大鹏', 1),
 ('龚建军', 1),
 ('叶朝纯', 1),
 ('周玉生', 1),
 ('汪恋', 1),
 ('朱峰', 1),
 ('张广军', 1),
 ('蒋文聪', 1),
 ('李孟锴', 1),
 ('徐礼', 1),
 ('汪正 ', 1),
 ('义志伟', 1),
 ('刘丽红', 1),
 ('杨松', 1),
 ('彭珊', 1),
 ('蒋嫦美', 1),
 ('吴云婷', 1),
 ('符勋', 1),
 ('李彬', 1),
 ('苏羽剑', 1),
 ('徐扬', 1),
 ('郭秀', 1),
 ('张立林', 1),
 ('徐意', 1),
 ('孙晓晖', 1),
 ('吴昌龙', 1),
 ('彭俊', 1),
 ('汤晓强', 1),
 ('曹文仂', 1),
 ('郭金丹', 1),
 ('赖开文', 1),
 ('陈丽', 1),
 ('曾玉芳', 1),
 ('刘坤', 1),
 ('樊明辉', 1),
 ('伍柳枝', 1),
 ('刘俊', 1),
 ('倪江平', 1),
 ('黄际怀', 1),
 ('钟志福', 1),
 ('全玲', 1),
 ('王佑玲', 1),
 ('何明明', 1),
 ('方平', 1),
 ('梁李理', 1),
 ('李新强', 1),
 ('刘娟', 1),
 ('秦桂炎', 1),
 ('徐灿', 1),
 ('胡心馨', 1),
 ('岑飞霞', 1),
 ('欧发生', 1),
 ('刘伟顺', 1),
 ('何焱', 1),
 ('颜杰', 1),
 ('王燕玲', 1),
 ('杨再平', 1),
 ('黄锱勇', 1),
 ('刘志恒', 1),
 ('刘宇', 1),
 ('周行', 1),
 ('邓丽', 1),
 ('张斯慧', 1),
 ('汤坤', 1),
 ('钟樟', 1),
 ('颜至清', 1),
 ('龙银冬', 1),
 ('周洪亮', 1),
 ('段强', 1),
 ('梁希', 1),
 ('王森', 1),
 ('唐雨微', 1),
 ('杨劲槐', 1),
 ('彭宏杰', 1),
 ('倪湾', 1),
 ('朱微', 1),
 ('龚洵重', 1),
 ('江杰英', 1),
 ('杨娇', 1),
 ('刘伟', 1),
 ('熊志颖', 1),
 ('谌玉连', 1),
 ('刘雅希', 1),
 ('林腊', 1),
 ('李炜', 1),
 ('聂嘉威', 1),
 ('杨炀', 1),
 ('魏翕成', 1),
 ('李浩宇', 1),
 ('杨黎军', 1),
 ('刘凯', 1),
 ('何赛', 1),
 ('黄敏', 1),
 ('郑利', 1),
 ('谭佳佳', 1),
 ('谢起', 1),
 ('刘志强', 1),
 ('唐健', 1),
 ('常宇舟', 1),
 ('李科', 1),
 ('刘延丽', 1),
 ('刘纯', 1),
 ('贺家鹏', 1),
 ('廖乐亮', 1),
 ('石涛', 1),
 ('张芬', 1),
 ('秦毕勇', 1),
 ('禹潮野', 1),
 ('肖安平', 1),
 ('陈锦锋', 1),
 ('罗龙涛', 1),
 ('蒋巧云', 1),
 ('李孝', 1),
 ('何丹', 1),
 ('马超', 1),
 ('燕虹江', 1),
 ('胡放明', 1),
 ('刘鑫', 1),
 ('潘玄', 1),
 ('罗裕杰', 1),
 ('龚开洋', 1),
 ('李志', 1),
 ('李勇', 1),
 ('刘杰', 1),
 ('刘旺', 1),
 ('汤燕飞', 1),
 ('汪海军', 1),
 ('罗成', 1),
 ('杨岳南', 1),
 ('柯江鸿', 1),
 ('曾淑英（曾可可）', 1),
 ('郭杰森', 1),
 ('杨建明', 1),
 ('黎银花', 1),
 ('叶贤冰', 1),
 ('王冀渝', 1),
 ('朱方青', 1),
 ('罗小南', 1),
 ('田小芬', 1),
 ('周卢', 1),
 ('薛瑞杨（薛瑞阳）', 1),
 ('张益嘉', 1),
 ('陈雪姣', 1),
 ('卿伟', 1),
 ('孟颖', 1),
 ('屈翠萍', 1),
 ('冯思思', 1),
 ('肖宜炎', 1),
 ('周培', 1),
 ('陈骞（陈骞亚）', 1),
 ('赵政国（赵洁）', 1),
 ('肖瑨', 1),
 ('朱兴', 1),
 ('刘小芳', 1)]

In [7]:
name=u'曾小纾'
a_id=[]
article=[]
read=[]
max_layers=[]
for index, row in data_0.iterrows():
    if row["Author"]==name:
        title=row["Title"]
        title="".join(title.split(' '))
        if title not in article:
            article.append(title)
            a_id.append(row["No"])
            read.append(row["Read"])
            max_layers.append(row["Max_layers"])
        else:
            i=article.index(title)
            read[i]=read[i]+row["Read"]
            max_layers[i]=max(max_layers[i],row["Max_layers"])
            
article_data=zip(a_id,read,max_layers)

In [8]:
list(article_data)

[(239, 12, 2),
 (499, 19, 2),
 (522, 56, 3),
 (550, 24, 2),
 (590, 23, 2),
 (621, 31, 2),
 (668, 26, 2),
 (686, 35, 3),
 (717, 60, 3),
 (738, 25, 2),
 (772, 21, 2),
 (804, 11, 2),
 (822, 58, 2),
 (854, 23, 2),
 (886, 27, 2),
 (914, 13, 2),
 (960, 30, 2),
 (1039, 44, 3),
 (1055, 1, 1),
 (1082, 40, 2),
 (1109, 19, 2),
 (1145, 23, 2),
 (1181, 18, 2),
 (1204, 29, 3),
 (1231, 33, 3),
 (1262, 40, 2),
 (1306, 76, 4),
 (1336, 15, 2),
 (1357, 32, 2),
 (1412, 4, 2),
 (1427, 16, 2),
 (1457, 46, 3),
 (1505, 1, 1),
 (1528, 25, 3),
 (1550, 23, 4),
 (1563, 19, 2),
 (1603, 49, 3),
 (1662, 13, 3),
 (1700, 36, 3),
 (1727, 71, 4),
 (1740, 45, 3),
 (1753, 33, 2),
 (1765, 2, 1),
 (1782, 62, 2),
 (1794, 48, 3),
 (1807, 15, 2),
 (1839, 16, 2),
 (1849, 44, 3),
 (1870, 35, 2),
 (1893, 6, 3),
 (1918, 52, 3),
 (1928, 57, 3),
 (1939, 55, 3),
 (1950, 55, 3),
 (1961, 5, 2),
 (2004, 1, 1),
 (2060, 44, 2),
 (2075, 1, 1),
 (2083, 5, 2),
 (2096, 14, 2),
 (2117, 21, 2),
 (2135, 46, 3),
 (2161, 42, 2),
 (2191, 15, 2),
 (2265, 38, 2),
 (2288, 24, 2),
 (2301, 21, 2),
 (2420, 19, 2),
 (2460, 36, 3),
 (2495, 1, 1),
 (2538, 33, 3),
 (2566, 24, 2),
 (2577, 34, 2),
 (2595, 33, 3),
 (2609, 34, 3),
 (2638, 55, 2),
 (2666, 30, 2),
 (2690, 15, 3),
 (2778, 27, 4),
 (2830, 27, 2),
 (2896, 31, 2),
 (2993, 61, 5),
 (3041, 23, 3),
 (3064, 15, 2),
 (3113, 22, 2),
 (3210, 16, 2),
 (3358, 12, 3),
 (3457, 13, 2),
 (3503, 16, 2),
 (3569, 25, 2),
 (3731, 29, 3),
 (3839, 15, 2),
 (4074, 16, 2),
 (4155, 14, 2),
 (4240, 57, 2),
 (4346, 15, 2),
 (4468, 13, 2),
 (4497, 9, 2),
 (4544, 16, 2),
 (4684, 19, 2),
 (4807, 8, 2),
 (4841, 7, 2),
 (4863, 8, 2),
 (5135, 23, 2),
 (5361, 5, 2),
 (5410, 4, 2),
 (5461, 13, 1),
 (5464, 6, 3),
 (5587, 21, 2),
 (5683, 14, 2),
 (5967, 12, 2),
 (6333, 25, 2),
 (6501, 16, 3),
 (6781, 6, 2),
 (6849, 22, 2),
 (7076, 8, 2),
 (7625, 13, 2),
 (7829, 4, 2),
 (7895, 9, 2),
 (8028, 5, 2),
 (8101, 15, 2),
 (8146, 9, 2),
 (10233, 15, 2)]