In [3]:
import mysql.connector
import pandas as pd
from sqlalchemy import create_engine

# Establish MySQL connection
conn = mysql.connector.connect(
    host="10.64.87.7",
    user="yjwang",
    password="YanjunWang-HKU",
    database="wechat_mingjiang",
    port="3306"
)

# Create SQLAlchemy engine
engine = create_engine('mysql+mysqlconnector://yjwang:YanjunWang-HKU@10.64.87.7:3306/wechat_mingjiang')

# Load table into a DataFrame using the engine
dep = pd.read_sql_table("agent_dep_job", con=engine)
dep

DatabaseError: 2003 (HY000): Can't connect to MySQL server on '10.64.87.7:3306' (10060)

In [4]:
# Filter rows where both agent_dep and agent_job are non-empty
dep_filtered = dep.dropna(subset=['agent_dep', 'agent_job'])  # Removes rows with NULL values
dep_filtered = dep_filtered[dep_filtered['agent_dep'].str.strip() != ""]  # Removes rows with empty strings in agent_dep
dep_filtered = dep_filtered[dep_filtered['agent_job'].str.strip() != ""]  # Removes rows with empty strings in agent_job
dep_filtered = dep_filtered.rename(columns={'agent': 'agent_name'})
# Compare the length of the original and filtered dataset
print(len(dep))
print(len(dep_filtered))

NameError: name 'dep' is not defined

In [ ]:
# Load table into a DataFrame using the engine
wechatnn = pd.read_sql_table("agent_wechatnn", con=engine)
wechatnn

In [ ]:
# Merge datasets using inner join
dep_wechatnn = pd.merge(dep_filtered, wechatnn, on='agent_name', how='inner')
dep_wechatnn

In [ ]:
print(len(wechatnn))
print(len(dep_wechatnn))

In [ ]:
detail = pd.read_sql_table("detail", con=engine)
detail_filtered = detail[detail['reader_gender'] != 2] # Without reader's gender equals to 2
print(len(detail))
print(len(detail_filtered))

In [ ]:
# Filter df_detail where reader_gender is not 2
valid_agents = detail_filtered['agent_name'].unique()

# Filter combined_df to keep only rows where agent_name matches valid_agents
filtered_dep_wenn = dep_wechatnn[dep_wechatnn['agent_name'].isin(valid_agents)]

In [ ]:
# The length of combined dataset which combined dep_job with wechatnn and filtered out the rows 
# that the agents in detail dataset do not have readers'gender
print(len(valid_agents))
print(len(filtered_dep_wenn))

In [10]:
detail_filtered1 = detail_filtered[detail_filtered['agent_name'].isin(filtered_dep_wenn['agent_name'])]
print(len(detail_filtered1))

258179

In [11]:
import pandas as pd
article_word = pd.read_csv('word_article_title_path.csv')
article_word.head()

,File Name,Title,Path
0,word_doc/幸福满庭80平.docx 13.6KB,幸福满庭80平,C:\Users\wangy\Downloads\word_doc-20250922T105...
1,word_doc/现代简约.docx 13.9KB,现代简约,C:/Users/wangy/Downloads/word_doc-20250922T105...
2,word_doc/装修前如何与设计师沟通_8个问题打造完美家装！.docx 5.7MB,装修前如何与设计师沟通_8个问题打造完美家装！,C:/Users/wangy/Downloads/word_doc-20250922T105...
3,word_doc/水墨林溪二期工程进度！.docx 21.9KB,水墨林溪二期工程进度！,C:/Users/wangy/Downloads/word_doc-20250922T105...
4,word_doc/欧式720°全景.docx 13.7KB,欧式720°全景,C:/Users/wangy/Downloads/word_doc-20250922T105...

In [22]:
detail_filtered2 = detail_filtered1[detail_filtered1['article_title'].isin(article_word['Title'])]
print(len(detail_filtered2))
detail_filtered2.head(30)

209895

,detail_index,article_title,agent_name,reader_wechat_nn,reader_layer,reader_address,reader_gender,reader_time,reader_stay,reader_share2moment,reader_share2friend,reader_read,network_parent
1350,1350,#名匠出品 必属精品#,赵林,赵·国际城G组团·负责专员,1,贵州贵阳,1,2017-09-28 05:36:14,0,0,0,3,
1351,1351,#名匠出品 必属精品#,赵林,完美love,1,上海,0,2017-08-23 05:54:00,0,0,0,1,
1352,1352,#名匠出品 必属精品#,赵林,琪琪,1,贵州贵阳,0,2017-08-22 21:55:05,30,0,0,1,
1353,1353,#名匠出品 必属精品#,赵林,陈俊东-名匠装饰-家装顾问,1,贵州贵阳,1,2017-08-23 05:55:17,0,0,0,1,
1354,1354,#名匠出品 必属精品#,赵林,丹,1,中国 贵州 贵阳,0,2017-08-23 05:56:55,0,0,0,1,
1355,1355,#名匠出品 必属精品#,赵林,刘行恩·名匠装饰18373832827,1,湖南娄底,1,2017-08-23 06:00:44,0,0,0,1,
1356,1356,#名匠出品 必属精品#,赵林,??MJ·陆文俊,1,贵州贵阳,1,2017-08-23 06:00:56,0,0,0,3,
1357,1357,#名匠出品 必属精品#,赵林,邓春.名匠装饰.主任设计师,1,贵州贵阳,1,2017-08-23 06:03:17,0,0,0,1,
1358,1358,#名匠出品 必属精品#,赵林,李扬-名匠装饰-家装顾问,1,贵州贵阳,1,2017-08-23 06:10:32,0,0,0,1,
1359,1359,#名匠出品 必属精品#,赵林,金牌标榜张平18786622376,1,中国 贵州 贵阳,0,2017-08-23 06:16:04,0,0,0,1,
1360,1360,#名匠出品 必属精品#,赵林,蒲公英,1,贵州贵阳,0,2017-08-23 06:22:20,30,0,0,1,
1362,1362,#名匠出品 必属精品#,赵林,廖明旦-名匠装饰-高级设计师,1,湖南邵阳,1,2017-08-23 06:38:49,0,0,0,1,
1363,1363,#名匠出品 必属精品#,赵林,吉長雨,1,中国 贵州 贵阳,1,2017-08-23 06:41:52,0,0,0,1,
1364,1364,#名匠出品 必属精品#,赵林,王哓蓉,1,中国 贵州 贵阳,0,2017-08-23 07:00:20,30,0,0,1,
1365,1365,#名匠出品 必属精品#,赵林,MJ～吴梦娇,1,贵州贵阳,0,2017-08-23 00:06:35,0,0,0,2,
1366,1366,#名匠出品 必属精品#,赵林,自由人,1,中国 贵州 贵阳,1,2017-08-23 10:32:42,0,0,0,1,
1367,1367,#名匠出品 必属精品#,赵林,yw,1,贵州贵阳,1,2017-08-23 21:53:47,0,0,0,1,
1368,1368,#名匠出品 必属精品#,赵林,gymj(rds)18984818524,1,贵州贵阳,1,2017-08-24 03:05:50,90,0,0,2,
1369,1369,#名匠出品 必属精品#[玫瑰] 面积：110平方,吴梦娇,MJ～吴梦娇,1,贵州贵阳,0,2017-09-01 01:02:54,30,1,0,2,
1370,1370,#名匠出品 必属精品#[玫瑰] 面积：110平方,吴梦娇,海,2,中国 贵州 贵阳,1,2017-08-23 08:14:31,30,0,0,1,MJ～吴梦娇
1371,1371,#名匠出品 必属精品#[玫瑰] 面积：110平方,吴梦娇,申瑞特 黄俊博,2,中国 贵州 贵阳,1,2017-08-23 08:17:35,30,0,0,1,MJ～吴梦娇
1374,1374,#名匠出品 必属精品#[玫瑰] 面积：110平方,吴梦娇,赵猛,2,贵州贵阳,1,2017-08-23 22:45:26,30,0,0,2,MJ～吴梦娇
1375,1375,#名匠出品 必属精品#[玫瑰] 面积：110平方,吴梦娇,莲,2,贵州贵阳,0,2017-08-23 12:02:38,0,0,0,1,MJ～吴梦娇
1376,1376,#名匠出品 必属精品#[玫瑰] 面积：110平方,吴梦娇,流水知音,2,中国 贵州 贵阳,1,2017-08-24 22:38:39,30,0,0,2,MJ～吴梦娇
1467,1467,108㎡优雅灰色装饰，考古、机械爱好者的家，真酷！,周志刚,MJ周志刚,1,湖南长沙,1,2018-07-14 09:08:08,60,0,0,1,
1468,1468,108㎡优雅灰色装饰，考古、机械爱好者的家，真酷！,周志刚,胡小铜,1,湖南长沙,0,2018-07-15 07:40:48,60,0,0,2,
1469,1469,108㎡优雅灰色装饰，考古、机械爱好者的家，真酷！,周志刚,MJ谭霖枫,1,湖南岳阳,1,2018-07-15 07:40:36,0,0,0,1,
1470,1470,108㎡优雅灰色装饰，考古、机械爱好者的家，真酷！,周志刚,超-炫兴,1,湖南长沙,1,2018-07-15 07:41:00,60,0,0,1,
1471,1471,108㎡优雅灰色装饰，考古、机械爱好者的家，真酷！,周志刚,邓经理,1,湖南长沙,1,2018-07-15 07:43:06,30,0,0,1,
1472,1472,108㎡优雅灰色装饰，考古、机械爱好者的家，真酷！,周志刚,S W,1,中国 湖南 长沙,1,2018-07-15 07:43:58,0,0,0,1,

In [13]:
len(detail_filtered1['article_title'].unique())

1345

In [26]:
article_word['Title'].nunique()

1421

In [25]:
detail_filtered2['article_title'].nunique()

1051

In [16]:
len(detail_filtered2[['article_title', 'agent_name']].drop_duplicates())

6942

In [20]:
detail_filtered2.to_excel("detail_filtered2.csv", index=False)

In [27]:
print(detail_filtered2.shape)
print(detail_filtered2['article_title'].nunique())
print(detail_filtered2['article_title'].head(10))
print(detail_filtered2.columns)

(209895, 13)
1051
1350    #名匠出品 必属精品#
1351    #名匠出品 必属精品#
1352    #名匠出品 必属精品#
1353    #名匠出品 必属精品#
1354    #名匠出品 必属精品#
1355    #名匠出品 必属精品#
1356    #名匠出品 必属精品#
1357    #名匠出品 必属精品#
1358    #名匠出品 必属精品#
1359    #名匠出品 必属精品#
Name: article_title, dtype: object
Index(['detail_index', 'article_title', 'agent_name', 'reader_wechat_nn',
       'reader_layer', 'reader_address', 'reader_gender', 'reader_time',
       'reader_stay', 'reader_share2moment', 'reader_share2friend',
       'reader_read', 'network_parent'],
      dtype='object')

In [8]:
import os
os.chdir(r"C:\Users\wangy")
import pandas as pd
df1 = pd.read_excel("wechat(S1)/detail_filtered2.xlsx")
df1.head()

In [10]:
df1.head()
print(df1['article_title'].nunique())

1051